### ISSUE TITLE
Install of qt5-webkit failing on Catalina

### ISSUE THREAD

**Issue by dakira** [markwu/homebrew-personal#2]
Hey, I tried this on Catalina and get the following output (compiling seems to go through without errors, but `make install` fails:

```
brew install qt5-webkit
==> Installing qt5-webkit from markwu/personal
==> Installing dependencies for markwu/personal/qt5-webkit: cmake
==> Installing markwu/personal/qt5-webkit dependency: cmake
==> Downloading https://homebrew.bintray.com/bottles/cmake-3.16.2.catalina.bottl
==> Downloading from https://akamai.bintray.com/7b/7b7d0cc5ceba524f0bea36285ab0c
######################################################################## 100.0%
==> Pouring cmake-3.16.2.catalina.bottle.tar.gz
==> Caveats
Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/cmake
==> Summary
🍺  /usr/local/Cellar/cmake/3.16.2: 6,015 files, 56.1MB
==> Installing markwu/personal/qt5-webkit
==> Cloning https://github.com/qt/qtwebkit.git
Cloning into '/Users/matthias/Library/Caches/Homebrew/qt5-webkit--git'...
Updating files: 100% (13182/13182), done.
==> Checking out branch 5.212
Already on '5.212'
Your branch is up to date with 'origin/5.212'.
==> Downloading https://raw.githubusercontent.com/markwu/homebrew-personal/maste
######################################################################## 100.0%
==> Patching
==> Applying qt5-webkit.diff
patching file Source/WTF/wtf/spi/darwin/XPCSPI.h
patching file Tools/qmake/projects/run_cmake.pro
==> /usr/local/opt/qt/bin/qmake ../WebKit.pro -config release -spec macx-clang
==> make
==> make install
Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory @ rb_file_s_rename - (/usr/local/Cellar/qt5-webkit/5.212/lib/qml/QtWebKit/libqmlwebkitplugin.so, /usr/local/Cellar/qt5-webkit/5.212/lib/qml/QtWebKit/libqmlwebkitplugin.dylib)
```

Any idea whats going on there?

**Comment by markwu** [comment]
I am not sure, I still stick with Mojave ...

Do you have more detail logs?

**Comment by dakira** [comment]
@markwu where would I get those? The above is the whole output of homebrew.

**Comment by markwu** [comment]
Can you try `brew install --verbose --debug qt5-webkit > install.log`?

It will print all debug information to install.log for further verification.

**Comment by dakira** [comment]
Here it is.
https://gist.github.com/dakira/953c6a342d4c33b3f357301fd3a041de

**Comment by markwu** [comment]
> The WebKit build was disabled for the following reasons:
    * QtWebKit requires an macOS SDK version of 10.10 or newer. Current version is .

I saw this, I have no idea what is that. Let me compile qtwebkit in mojave again to see any different.

Can you show me the full `install.log`?

BTW, what is your xcode and clt version? You can run `brew config` for more detail.

**Comment by markwu** [comment]
I compiled again, and didn't see the message above.

**Comment by dakira** [comment]
I tried on a blank Catalina machine and get the same message. Google doesn't help much, unfortuntely. Xcode and the cmd line utilities are installed, of course. I wonder what SDK they're talking about.
```
HOMEBREW_VERSION: 2.2.3
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8398d0b2db3146b2b3179c5d03ac72a28c90ce56
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f2463cbba086689c872cddd3a8bc242976a603ff
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BREW_GIT_REMOTE: https://github.com/Homebrew/brew
HOMEBREW_CORE_GIT_REMOTE: https://github.com/Homebrew/homebrew-core
CPU: quad-core 64-bit kabylake
Homebrew Ruby: 2.6.3 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
Clang: 11.0 build 1100
Git: 2.24.0 => /usr/local/bin/git
Curl: 7.64.1 => /usr/bin/curl
Java: 10.0.1
macOS: 10.15.2-x86_64
CLT: 11.0.33.16
Xcode: 11.3.1
```

**Comment by dakira** [comment]
Found the problem! qmake can't find the SDK when the xcode command line tools were installed **before** xcode itself was installed (e.g. set up new mac, install Homebrew and only after that install Xcode).

To fix that, the path of the command line tools can be changed as described [here](https://stackoverflow.com/questions/17980759/xcode-select-active-developer-directory-error/17980786#17980786):

    sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

**Comment by dakira** [comment]
@markwu thanks for helping and pointing me in the right direction!

**Comment by markwu** [comment]
@dakira Thank you let me know this.
